In [1]:
print('Hello world')

Hello world


In [2]:
global str

string = "Hello, World!"
print(string)
print(string[0])
print(string[2:5])
print(string[2:])
print(string*2)
print(string + "!!")

Hello, World!
H
llo
llo, World!
Hello, World!Hello, World!
Hello, World!!!


In [3]:
list1 = ["mary", 258, 13.67, "text", 12]
list2 = [158, "mary"]

print(list1)
print(list2)

print (list1[0])
print (list1[1:3])
print (list1[2:])
print (list2 *2)
print (list1 + list2)

['mary', 258, 13.67, 'text', 12]
[158, 'mary']
mary
[258, 13.67]
[13.67, 'text', 12]
[158, 'mary', 158, 'mary']
['mary', 258, 13.67, 'text', 12, 158, 'mary']


In [4]:
tuple1 = ('mary', 258, 13.67, 'text', 12)
tuple2 = (158, 'mary')

print (tuple1)
print (tuple2)

print (tuple1[0])
print (tuple1[1:3])
print (tuple1[2:])
print (tuple2 * 2)
print (tuple1 + tuple2)

('mary', 258, 13.67, 'text', 12)
(158, 'mary')
mary
(258, 13.67)
(13.67, 'text', 12)
(158, 'mary', 158, 'mary')
('mary', 258, 13.67, 'text', 12, 158, 'mary')


In [5]:
dict1 = {}
dict1['one'] = "This is one"
dict1[2] = "This is two"

dict2 = {'name': 'john', 'code': 6734, 'dept': 'sales'}

print (dict1)
print (dict1['one'])
print (dict1[2])

print (dict2)
print (dict2.keys())
print (dict2.values())

{'one': 'This is one', 2: 'This is two'}
This is one
This is two
{'name': 'john', 'code': 6734, 'dept': 'sales'}
dict_keys(['name', 'code', 'dept'])
dict_values(['john', 6734, 'sales'])


In [6]:
valor = 0

valor += 3

valor -= 1

valor *= 3

valor /= 2

valor %= 2

valor **= 5

valor //= 2

print (valor)

0.0


In [7]:
age = 32
salary = 35000
print((age > 25) and (salary > 40000))

False


In [8]:
s = 'This is a string'

for c in s:
    print (c, end= " ")
    
print ('p' in s)
print (' ' in s)
print ('y' in s)

print (s)

T h i s   i s   a   s t r i n g False
True
False
This is a string


In [9]:
a = 10
b = 20
list = [1, 2, 3, 4, 5]

if (a in list):
    print("a is available in the given list")
else:
    print("a is not available in the given list")
    
if (b not in list):
    print("b is not available in the given list")
else:
    print("b is available in the given list")

a is not available in the given list
b is not available in the given list


In [10]:
a = 20
b = 20

if a is b:
    print("a and b have same identity")
else:
    print("a and b do not have same identity")
    
if id(a) == id(b):
    print("a and b have same identity")
else:
    print("a and b do not have same identity")
    
b = 30

if a is b:
    print("a and b have same identity")
else:
    print("a and b do not have same identity")

a and b have same identity
a and b have same identity
a and b do not have same identity


In [11]:
score = float(input("Enter score: "))

if score >= 50:
    print('Pass')
else:
    print('Fail')

Enter score: 20
Fail


In [12]:
score = float(input("Enter score: "))

if score >= 90:
    grade = 'A'
else:
    if score >= 80:
        grade = 'B'
    else:
        if score >= 70:
            grade = 'C'
        else:
            if score >= 60:
                grade = 'D'
            else:
                grade = 'E'
                
print('\nGrade is: %s' % grade)

Enter score: 56

Grade is: E


In [13]:
score = float(input("Enter score: "))

if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
elif score >= 60:
    grade = 'D'
else:
    grade = 'E'
    
print('\nGrade is: %s' % grade)

Enter score: 67

Grade is: D


In [14]:
total = 0.0
count = 0

while count < 10:
    number = float(input("Enter a number: "))
    count = count + 1
    total = total + number
    
average = total / count
print("The average is " + str(average))

Enter a number: 20
Enter a number: 60
Enter a number: 25
Enter a number: 85
Enter a number: 100
Enter a number: 10
Enter a number: 15
Enter a number: 18
Enter a number: 16
Enter a number: 24
The average is 37.3


In [15]:
for x in range(0, 5):
    print ("Index %d" % (x))

Index 0
Index 1
Index 2
Index 3
Index 4


In [16]:
for x in range(1, 11):
    for y in range(1, 11):
        print("%d * %d = %d" % (x, y, x*y))

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90
10 * 1 = 10
10 * 2 = 20


In [17]:
for x in range(3):
    print(x)
    if x == 1:
        break

0
1


In [18]:
fruits = ['strawberry', 'banana', 'apple', 'mango']

for index in range(len(fruits)):
    print('Current fruit :', fruits[index])
    
print("Goodbye!")

Current fruit : strawberry
Current fruit : banana
Current fruit : apple
Current fruit : mango
Goodbye!


In [19]:
def print_result(score):
    if score >= 50:
        print('Pass')
    else:
        print('Fail')
    return

In [20]:
print_result(51)

Pass


In [21]:
var = 30
def escopo():
    var1 = 50
    print("Dentro da função - variável local " + str(var1))
    print("Dentro da função - variável global " + str(var))

def escopo1():
    var2 = 40
    print("Dentro da função - variável global " + str(var))
    print("Dentro da função - v ariável local de escopo1" + str(var2))
    print("Dentro da função - variável local de escopo" + str(var1))
    
escopo()
    
print("Fora da função - variavél global " + str(var))
print("Fora da função - variavél local " + str(var1))

Dentro da função - variável local 50
Dentro da função - variável global 30
Fora da função - variavél global 30


NameError: name 'var1' is not defined

In [22]:
!pip install numpy

     |████████████████████████████████| 15.3 MB 4.4 MB/s eta 0:00:01


In [23]:
import numpy as np

In [26]:
a = np.zeros(shape=(3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
a[0] = [1,2]
a[1] = [2,3]
a

array([[1., 2.],
       [2., 3.],
       [0., 0.]])

In [28]:
a[2][1] = 8
a

array([[1., 2.],
       [2., 3.],
       [0., 8.]])

In [30]:
b = np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
b[0][2] = 6
b[1][2] = 6
b[2][2] = 6
b

array([[1., 1., 6., 1.],
       [1., 1., 6., 1.],
       [1., 1., 6., 1.]])

In [34]:
x = np.ones((3,4))
print(x.shape)

(3, 4)


In [35]:
np.zeros((2,3,4), dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [36]:
np.random.random((2,2))

array([[0.66879846, 0.94740178],
       [0.53647212, 0.81098699]])

In [38]:
np.empty((3,2))

array([[4.66619274e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [40]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [41]:
np.arange(10,25,5)

array([10, 15, 20])

In [43]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [44]:
a

array([[1., 2.],
       [2., 3.],
       [0., 8.]])

In [46]:
a.sum()

16.0

In [47]:
a.min()

0.0

In [48]:
a.max()

8.0

In [49]:
a.max(axis=0)

array([2., 8.])

In [50]:
a.max(axis=1)

array([2., 3., 8.])

In [51]:
a.cumsum(axis=1)

array([[1., 3.],
       [2., 5.],
       [0., 8.]])

In [52]:
a.cumprod()

array([ 1.,  2.,  4., 12.,  0.,  0.])

In [53]:
a.mean()

2.6666666666666665

In [54]:
a.var()

6.555555555555556